### ISSUE TITLE
在partial-iLIDS数据集上测试报错

### ISSUE THREAD

**Issue by Tord-Zhang** [yolomax/person-reid-lib#12]
你好，

我尝试使用在market1501训练好的模型在Partial-iLIDS上测试，Partial-iLIDS是一个比较特殊的数据集，在query和gallery中，每个person都只有一个cam，在测试时，已经给出了warning,最后测试时报错。报错信息如下，请问你知道为什么会出现这种情况吗，难道要求每个人必须多个cam？谢谢！

2020-05-11 17:53:59,583 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 117
2020-05-11 17:53:59,583 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 22
2020-05-11 17:53:59,583 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 112
2020-05-11 17:53:59,583 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 54
2020-05-11 17:53:59,584 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 13
2020-05-11 17:53:59,584 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 39
2020-05-11 17:53:59,584 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 118
2020-05-11 17:53:59,584 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 37
2020-05-11 17:53:59,584 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 74
2020-05-11 17:53:59,584 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 11
2020-05-11 17:53:59,584 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 46
2020-05-11 17:53:59,584 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 53
2020-05-11 17:53:59,585 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 20
2020-05-11 17:53:59,585 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 44
2020-05-11 17:53:59,585 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 83
2020-05-11 17:53:59,585 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 90
2020-05-11 17:53:59,585 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 43
2020-05-11 17:53:59,585 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 91
2020-05-11 17:53:59,585 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 96
2020-05-11 17:53:59,585 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 40
2020-05-11 17:53:59,586 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 21
2020-05-11 17:53:59,586 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 34
2020-05-11 17:53:59,586 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 50
2020-05-11 17:53:59,586 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 114
2020-05-11 17:53:59,586 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 62
2020-05-11 17:53:59,586 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 77
2020-05-11 17:53:59,586 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 80
2020-05-11 17:53:59,586 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 42
2020-05-11 17:53:59,587 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 113
2020-05-11 17:53:59,587 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 30
2020-05-11 17:53:59,587 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 66
2020-05-11 17:53:59,587 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 79
2020-05-11 17:53:59,587 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 107
2020-05-11 17:53:59,587 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 92
2020-05-11 17:53:59,587 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 33
2020-05-11 17:53:59,587 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 49
2020-05-11 17:53:59,588 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 87
2020-05-11 17:53:59,588 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 81
2020-05-11 17:53:59,588 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 52
2020-05-11 17:53:59,588 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 70
2020-05-11 17:53:59,588 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 103
2020-05-11 17:53:59,588 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 115
2020-05-11 17:53:59,588 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 23
2020-05-11 17:53:59,588 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 93
2020-05-11 17:53:59,589 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 32
2020-05-11 17:53:59,589 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 119
2020-05-11 17:53:59,589 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 1
2020-05-11 17:53:59,589 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 36
2020-05-11 17:53:59,589 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 5
2020-05-11 17:53:59,589 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 18
2020-05-11 17:53:59,589 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 31
2020-05-11 17:53:59,589 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 4
2020-05-11 17:53:59,590 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 64
2020-05-11 17:53:59,590 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 105
2020-05-11 17:53:59,590 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 9
2020-05-11 17:53:59,590 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 109
2020-05-11 17:53:59,590 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 10
2020-05-11 17:53:59,590 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 17
2020-05-11 17:53:59,590 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 60
2020-05-11 17:53:59,590 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 82
2020-05-11 17:53:59,591 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 111
2020-05-11 17:53:59,591 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 95
2020-05-11 17:53:59,591 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 86
2020-05-11 17:53:59,591 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 73
2020-05-11 17:53:59,591 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 12
2020-05-11 17:53:59,591 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 2
2020-05-11 17:53:59,591 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 56
2020-05-11 17:53:59,591 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 61
2020-05-11 17:53:59,592 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 15
2020-05-11 17:53:59,592 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 35
2020-05-11 17:53:59,592 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 110
2020-05-11 17:53:59,592 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 48
2020-05-11 17:53:59,592 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 72
2020-05-11 17:53:59,592 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 58
2020-05-11 17:53:59,592 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 99
2020-05-11 17:53:59,592 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 67
2020-05-11 17:53:59,593 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 55
2020-05-11 17:53:59,593 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 8
2020-05-11 17:53:59,593 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 104
2020-05-11 17:53:59,593 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 29
2020-05-11 17:53:59,593 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 71
2020-05-11 17:53:59,593 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 84
2020-05-11 17:53:59,593 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 27
2020-05-11 17:53:59,593 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 68
2020-05-11 17:53:59,594 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 88
2020-05-11 17:53:59,594 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 24
2020-05-11 17:53:59,594 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 25
2020-05-11 17:53:59,594 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 65
2020-05-11 17:53:59,594 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 106
2020-05-11 17:53:59,594 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 59
2020-05-11 17:53:59,594 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 102
2020-05-11 17:53:59,594 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 14
2020-05-11 17:53:59,594 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 6
2020-05-11 17:53:59,595 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 89
2020-05-11 17:53:59,595 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 94
2020-05-11 17:53:59,595 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 116
2020-05-11 17:53:59,595 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 41
2020-05-11 17:53:59,595 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 97
2020-05-11 17:53:59,595 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 3
2020-05-11 17:53:59,595 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 85
2020-05-11 17:53:59,595 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 78
2020-05-11 17:53:59,596 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 51
2020-05-11 17:53:59,596 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 26
2020-05-11 17:53:59,596 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 100
2020-05-11 17:53:59,596 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 38
2020-05-11 17:53:59,596 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 63
2020-05-11 17:53:59,596 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 101
2020-05-11 17:53:59,596 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 16
2020-05-11 17:53:59,596 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 47
2020-05-11 17:53:59,597 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 45
2020-05-11 17:53:59,597 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 69
2020-05-11 17:53:59,597 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 57
2020-05-11 17:53:59,597 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 98
2020-05-11 17:53:59,597 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 108
2020-05-11 17:53:59,597 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 76
2020-05-11 17:53:59,597 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 75
2020-05-11 17:53:59,597 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 7
2020-05-11 17:53:59,598 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 28
2020-05-11 17:53:59,598 - __init__.py[line:136] - WARNING: All gallery trackets have the same camera id with probe tracklet for ID： 19
data bank created
2020-05-11 17:53:59,600 - __init__.py[line:32] - INFO: Train Generator : AllTripletSampler
2020-05-11 17:53:59,600 - __init__.py[line:39] - INFO: Test Generator : TestSampler
2020-05-11 17:53:59,600 - __init__.py[line:37] - INFO: ---------------Choose eval rule EvalStandard----------------
2020-05-11 17:54:00,242 - resnet50.py[line:21] - INFO: Model restored from pretrained resnet50
2020-05-11 17:54:35,315 - netbase.py[line:51] - INFO: ------Output shape--------
2020-05-11 17:54:35,316 - netbase.py[line:53] - INFO: backbone feature dim: 2048
2020-05-11 17:54:35,316 - netbase.py[line:53] - INFO: final feature dim: 2048
2020-05-11 17:54:35,316 - netbase.py[line:55] - INFO: ----Parameter shape-------
2020-05-11 17:54:35,316 - netbase.py[line:57] - INFO: torch.Size([512, 2048])
2020-05-11 17:54:35,316 - netbase.py[line:57] - INFO: torch.Size([512])
2020-05-11 17:54:35,316 - netbase.py[line:57] - INFO: torch.Size([512])
2020-05-11 17:54:35,316 - netbase.py[line:57] - INFO: torch.Size([512])
2020-05-11 17:54:35,316 - netbase.py[line:57] - INFO: torch.Size([751, 512])
2020-05-11 17:54:35,316 - netbase.py[line:57] - INFO: torch.Size([751])
2020-05-11 17:54:35,316 - netbase.py[line:59] - INFO: --------------------------
2020-05-11 17:54:35,469 - netbase.py[line:140] - INFO: Model restored from /home/zt/pjob/person-reid-lib-master/tasks/task_viper/output/model/model.pkl
network loaded
2020-05-11 17:54:35,470 - solverbase.py[line:137] - INFO: Test Begin
Traceback (most recent call last):
  File "train_test.py", line 47, in <module>
    main()
  File "train_test.py", line 34, in main
    train_test_time = timer_lite(task.run)
  File "/home/zt/pjob/person-reid-lib-master/tasks/task_viper/../../lib/utils/meter.py", line 42, in timer_lite
    func()
  File "/home/zt/pjob/person-reid-lib-master/tasks/task_viper/../../lib/network/solver_factory/solverbase.py", line 86, in run
    self.test()
  File "/home/zt/pjob/person-reid-lib-master/tasks/task_viper/../../lib/network/solver_factory/solverbase.py", line 131, in test
    self.do_eval(network, self.test_batch_size)
  File "/home/zt/pjob/person-reid-lib-master/tasks/task_viper/../../lib/network/solver_factory/solverbase.py", line 149, in do_eval
    result = self.eval(network, batch_size)
  File "/home/zt/pjob/person-reid-lib-master/tasks/task_viper/../../lib/utils/decoratorbox.py", line 28, in wrapper
    result = func(cls, *args, **kwargs)
  File "/home/zt/pjob/person-reid-lib-master/tasks/task_viper/../../lib/network/solver_factory/solverbase.py", line 145, in eval
    result = self.evaluator.final_result()
  File "/home/zt/pjob/person-reid-lib-master/tasks/task_viper/../../lib/evaluation/__init__.py", line 61, in final_result
    cmc, mAP, avgSame, avgDiff, distMat = self._eval_manager.final_result()
  File "/home/zt/pjob/person-reid-lib-master/tasks/task_viper/../../lib/evaluation/evaluation_rule/eval_base.py", line 96, in final_result
    cmc, mAP = self._get_cmc_mAP(distMat.copy())
  File "/home/zt/pjob/person-reid-lib-master/tasks/task_viper/../../lib/evaluation/evaluation_rule/eval_standard.py", line 78, in _get_cmc_mAP
    cmc, mAP = eval_market1501_wrap(distMat, self.probe_id, self.gallery_id, self.probe_cam_id, self.gallery_cam_id, max_rank=20)
  File "eval.pyx", line 7, in cython_eval.eval_market1501_wrap
  File "eval.pyx", line 18, in cython_eval.eval_market1501_wrap
  File "eval.pyx", line 100, in cython_eval.eval_market1501
AssertionError: Error: all query identities do not appear in gallery

**Comment by yolomax** [comment]
在一般的数据集里面，query图片是不与同一个相机ID下的数据算匹配性能的，所以我加了这个检查。你这个有特殊需求的话，可以将 person-reid-lib/lib/dataset/__init__.py 中的182行注释掉。另外你要单独修改你指定的测试协议，即person-reid-lib/lib/evaluation/evaluation_rule中的性能评估代码，我给的代码里面都是排除同一个相机ID下数据匹配的。比如person-reid-lib/lib/evaluation/evaluation_rule/eval_standard.py 的第40行开始的code.
